- dataprep/eda/basic/compute.py
- dataprep/eda/basic/render.py
fixed bugs that arose when a numerical column was set as categorical
Briefly tested on suicides and adult datasets.
> fix(eda-basic): fixed  bugs when numerical column set as categorical

- .pylintrc
- dataprep/eda/correlation/compute.py
> fix(eda-correlation): optimize the correlation calculation of scatter

- dataprep/eda/missing/compute.py
- dataprep/eda/missing/render.py
> fix(eda.missing): Fix the label order and boxplot color

- dataprep/eda/correlation/compute.py
- dataprep/eda/correlation/render.py
> fix(eda.correlation): it works for the columns with missing values

- dataprep/eda/basic/render.py
- dataprep/eda/intermediate.py
Changed histogram xtics to make them more beautiful. #38 
Manually
> fix(eda-basic): fixed xtics for histograms

- dataprep/eda/correlation/compute.py
Committer: waterpine <songbian@zju.edu.cn>
> fix(eda.correlation): fix scatter and top-k nan

- dataprep/eda/basic/render.py
> fix(eda-basic): fixed xtic rounding

- dataprep/eda/basic/compute.py
- dataprep/eda/basic/render.py
Fixed casting to string. Now we only cast if needed. Also fixed basic dask efficiency things based on recommended best practices.
Manually on a few datasets
> fix(eda-basic): improved plot(df) efficiency

- dataprep/eda/missing/__init__.py
- dataprep/eda/missing/compute.py
> fix(eda.missing): fix parameter names

- dataprep/data_connector/connector.py
> feat(data_connector): show_schema()

- .gitmodules
- dataprep/data_connector/implicit_database.py
- dataprep/data_connector/types.py
These are minor fixes about the library structure.
> Minor fixes

- dataprep/eda/basic/__init__.py
- dataprep/eda/basic/render.py
- dataprep/eda/correlation/__init__.py
- dataprep/eda/missing/__init__.py
- dataprep/eda/report.py
- dataprep/tests/eda/test_plot.py
- dataprep/tests/eda/test_plot_correlation.py
- dataprep/tests/eda/test_report.py
This PR provides a uniform `Report` object so that we can have control of how and where the plots are rendered.
Fill me later.
> EDA: Report

- .pylintrc
- dataprep/eda/basic/__init__.py
- dataprep/eda/basic/compute.py
- dataprep/eda/basic/render.py
- dataprep/eda/dtypes.py
- dataprep/tests/eda/test_plot.py
Added support for time series plots from the issue #129.
Minimal manual testing on some Covid-19 datasets and added tests to test_plot.
> feat(eda.basic): added time series plots, support

- .circleci/config.yml
- .coveragerc
- .gitignore
- README.md
- codecov.yaml
- poetry.lock
- pyproject.toml
Add code coverage metric as a badge.
> ci: add codecov

- dataprep/eda/basic/__init__.py
- dataprep/eda/basic/compute.py
- dataprep/eda/basic/render.py
Changed the bandwidth to be the default in the KDE calculation, fixes issue #127. Also, did a couple minor code changes for efficiency and clarity.
Minimal testing on a couple datasets.
> fix(eda.basic): fixed kde calculation

- dataprep/eda/missing/compute.py
- dataprep/eda/utils.py
> fix(eda.plot_missing): handle int column name

- dataprep/eda/report.py
This PR fixes #152
Locally tested.
> Add render method to force render

- dataprep/eda/basic/compute.py
Split eda.basic.compute() into more functions based on the number of columns specified in plot()
Manually
> refactor(eda.plot): compute into more functions

- dataprep/eda/basic/compute.py
- dataprep/eda/basic/render.py
Closes #157
plot() now can generate statistical information according to the data type of specified column
Test scripts
> feat(eda.plot): plot() now can generate statistical information

- dataprep/eda/basic/compute.py
- dataprep/eda/basic/render.py
Resolve #166
plot(df) can generate a new section above the plots, shows statistical information for the dataset.
This section can be toggled on or off via the button on the top.
Test scripts.
> feat(eda.plot): plot(df) now can compute statistical information

- dataprep/eda/__init__.py
- dataprep/eda/basic/__init__.py
- dataprep/eda/basic/compute.py
- dataprep/eda/basic/render.py
- dataprep/eda/dtypes.py
- dataprep/eda/missing/__init__.py
- dataprep/eda/missing/compute.py
- dataprep/eda/missing/render.py
- dataprep/tests/eda/test.py
- dataprep/tests/eda/test_plot.py
- dataprep/tests/eda/test_plot_missing.py
plot() and plot_missing() now can generate graphs according to the data
types specified by users.
Two unit tests have been created for plot() and plot_missing().
> feat(eda):  support specifying column types

- dataprep/data_connector/connector.py
- dataprep/data_connector/errors.py
- dataprep/data_connector/implicit_database.py
- dataprep/data_connector/schema.json
- dataprep/tests/data_connector/test_integration.py
> Implement pagination for data_connector

- dataprep/eda/missing/__init__.py
- dataprep/eda/missing/compute.py
- dataprep/eda/missing/render.py
- dataprep/eda/utils.py
Please do not merge this branch. The development is still in progress.
This is just for collaboration purposes.
> feat(eda.plot_missing) Stage 1 adding heatmap (#168)

- dataprep/eda/__init__.py
- dataprep/eda/report.py
- poetry.lock
- pyproject.toml
Previously the Report class is rendered with the whole HTML documentation from bokeh `save`. This will inject duplicate bokeh scripts which cause problem.
fixes #102 #147 
Manually
No snapshots.
> fix(eda): fix the plot doesn't show up

- dataprep/eda/basic/compute.py
- dataprep/eda/basic/render.py
Fix the word cloud requires at least 1 word issue. Won't generate word cloud and word frequency tabs when there is no word after cleaning. Fix the index issue. Change the layout of stats.
Fixed #208
Passed the current unit tests
- [ X I have commented my code, particularly in hard-to-understand areas
> fix(eda.plot): fix plot(df,x) errors

- dataprep/eda/create_report/formatter.py
Key name in `itmdt` changed but `formatter` was not updated.
Manually
N/A
> fix(eda.create_report): update key name

- dataprep/eda/basic/compute.py
- dataprep/eda/dtypes.py
- dataprep/eda/missing/render.py
Add a function to remove NA/Null values from a Pandas/Dask dataframe or series.
Tried to fix issue #180 . Added a custom function to drop the NA/NULL values from a Pandas/Dask DataFrame or Series. 
This was tested on the Titanic dataset (using both .csv and xlsx file types).
> feat(eda) : add a drop_null function

- docs/source/_static/images/create_report/overview.html
- docs/source/_static/images/create_report/variables_num.html
- docs/source/user_guide/eda/create_report.rst
Fixed missing links in documentation due to folder structure change.
Local build
> docs: fixed missing links

- dataprep/eda/__init__.py
- dataprep/eda/create_report/formatter.py
- dataprep/eda/distribution/__init__.py
- dataprep/eda/distribution/compute.py
- dataprep/eda/distribution/render.py
- poetry.lock
- pyproject.toml
This increases the performance of `plot()` by tweaking dask.
Performance comparison with the current code (old), and with the changes from this branch (new). Used the adult dataset with duplication, loaded with `df = pd.read_csv("https://www.openml.org/data/get_csv/1595261/phpMawTba", na_values = [' ?'])`.
> perf(eda.plot): optimize plot() performance by tweaking dask

- .gitignore
- Justfile
- dataprep/data_connector/connector.py
- dataprep/data_connector/implicit_database.py
- dataprep/data_connector/throttle.py
- dataprep/tests/data_connector/test_integration.py
- poetry.lock
- pyproject.toml
applied async/await and fetched multiple pages in parallel
Fix: #192 and #193 
Works, however, is currently running into an error regarding rate limit. 
Using the test_intergration.py
> feat(data_connector) applied async/await and fetched multiple pages in parallel

- dataprep/eda/create_report/__init__.py
- dataprep/eda/create_report/formatter.py
- dataprep/eda/create_report/io.py
- dataprep/eda/create_report/templates/base.html
- dataprep/eda/create_report/templates/overview.html
- dataprep/eda/create_report/templates/scripts.html
- dataprep/eda/create_report/templates/styles.html
- dataprep/eda/create_report/templates/variables.html
- dataprep/eda/distribution/compute.py
- dataprep/eda/distribution/render.py
- dataprep/tests/eda/test_create_report.py
- docs/source/_static/images/create_report/variables_cat.html
- docs/source/_static/images/create_report/variables_num.html
- docs/source/user_guide/eda/create_report.rst
``` python
report = create_report(df)
report # this will show report in notebook
report.save() # this will save report
report.show_browser() # this will open report in the browser
```
Resolve #280 and #270
Test scripts.
N/A
> feat(eda.create_report): new report object for saving and showing report

- dataprep/eda/missing/compute.py
- dataprep/eda/missing/render.py
Fix for issue #286. 
Column: Occupation
Missing: 1000
Missing percent: 98%. **please have a look the screenshots below**
Tested on datasets, seems to be working. N
Please have a look at the hover tool tip and let me know if it looks okay. 
**note** : `poetry run pytest dataprep` fails on the eda module. Not sure if it has to anything with `plot_missing`,below is the screenshot.
> style(plot_missing): improvements to bar_charts in plot_missing

- dataprep/eda/distribution/compute.py
- dataprep/eda/distribution/render.py
- dataprep/eda/dtypes.py
Add distributional insights to plot(df) function
Closed #203 and #199
Passed all the current unit tests
> feat(eda.plot): Add auto insights stage 1

- dataprep/eda/container.py
- dataprep/eda/create_report/__init__.py
- dataprep/eda/create_report/io.py
- dataprep/eda/distribution/__init__.py
- dataprep/eda/distribution/compute.py
- dataprep/eda/distribution/render.py
- dataprep/eda/distribution/templates/base.html
- dataprep/eda/distribution/templates/scripts.html
- dataprep/eda/distribution/templates/styles.html
- dataprep/eda/report.py
The `plot(df)` function now has a brand new interface.
Close #241
test scripts
> feat(eda.plot): Redesigned layout for plot(df)

- README.md
Updated Connector readme descriptions
> connector: updated readme

- dataprep/eda/create_report/formatter.py
- dataprep/eda/distribution/compute/univariate.py
- dataprep/eda/distribution/render.py
Added insights for `plot(df, x)`. Closes #203.
Minimal manual testing, and the unit tests
> feat(eda.plot): insights for plot(df, x)

- dataprep/eda/distribution/compute/__init__.py
- dataprep/eda/distribution/render.py
Fixed the wordcloud to work on bokeh version > 2.0.2. And added a fix for all nan columns. Closes #299
> fix(eda.plot): fixed wordcloud, all nan column

- dataprep/eda/__init__.py
- dataprep/eda/correlation/__init__.py
- dataprep/eda/correlation/compute/common.py
- dataprep/eda/correlation/compute/univariate.py
- dataprep/eda/distribution/__init__.py
- dataprep/eda/missing/__init__.py
- dataprep/eda/progress_bar.py
Add progress bar to improve user experience.
locally
> feat(eda): add progress bar for dask local scheduler

- dataprep/eda/distribution/compute/bivariate.py
- dataprep/eda/distribution/compute/common.py
- dataprep/eda/distribution/compute/overview.py
- dataprep/eda/distribution/render.py
Optimize `plot(df, x, y)`. Closes #148 and closes #123
> perf(eda.plot): optimize bivariate computations

- dataprep/eda/correlation/compute/nullivariate.py
- dataprep/eda/correlation/render.py
- dataprep/eda/create_report/formatter.py
- dataprep/eda/distribution/compute/common.py
- dataprep/eda/distribution/compute/overview.py
- dataprep/eda/distribution/compute/univariate.py
- dataprep/eda/distribution/render.py
- dataprep/eda/dtypes.py
- dataprep/eda/missing/compute.py
- dataprep/eda/missing/render.py
- dataprep/tests/eda/test_create_report.py
- dataprep/tests/eda/test_plot.py
Refactor create_report to use dask effectively. Note error handling is not implemented as it was before. 
Tested on
``` python
df = pd.read_csv("https://www.openml.org/data/get_csv/1595261/phpMawTba", na_values = [' ?'])
df = pd.read_csv("https://www.openml.org/data/get_csv/4965268/wine-quality-red.arff")
df = pd.read_csv("https://www.openml.org/data/get_csv/16826755/phpMYEkMl", na_values = ['?'])
df = pd.read_csv("https://raw.githubusercontent.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning/master/covid_19_clean_complete.csv")
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00291/airfoil_self_noise.dat', sep="\t", names = ['Frequency','Angle of attack','Chord length','Free-stream velocity','Suction/side','Scaled/sound'])
df = …
```
> refactor(eda.create_report): optimize create_report

- dataprep/eda/distribution/render.py
The pie chart insight is when the largest category is *x* times bigger than the second-largest category; this PR checks that there are at least two categories in the column. Closes #321
> fix(eda.distribution): fix pie chart insight

- dataprep/clean/__init__.py
- dataprep/clean/clean_lat_long.py
- dataprep/clean/utils.py
Function to clean latitude and longitude coordinates. 
Functionality:
specify output format
split into two columns
split and specify the format
Clean only one coordinate
> feat(clean): clean latitude, longitude coordinates

- docs/source/user_guide/clean/clean_lat_long.ipynb
Added to the user guide for the clean_lat_long and validate_lat_long functions.
closes #329
Completed the user guide for the clean_lat_long and validate_lat_long methods.
Manually ran the examples in a Jupiter notebook.
> docs(cleaning): update clean_lat_long docs

- dataprep/connector/connector.py
- dataprep/connector/implicit_database.py
- dataprep/connector/ref.py
- dataprep/connector/schema/defs.py
Adding ContinuationToken support for pagination. Related to #215 
It has been tested on Youtube API.
> feat(data_connector): adding ContinuationToken support for pagination

- dataprep/clean/__init__.py
- dataprep/clean/clean_email.py
- dataprep/clean/utils.py
Supports cleaning and validation function for semantic data type Email.
> feat(clean): add clean_email() function

- docs/source/user_guide/clean/clean_email.ipynb
- docs/source/user_guide/clean/introduction.ipynb
> docs(clean): add documentation for clean_email()

- dataprep/eda/correlation/compute/__init__.py
- dataprep/eda/correlation/compute/bivariate.py
- dataprep/eda/distribution/compute/bivariate.py
- dataprep/eda/distribution/render.py
- dataprep/eda/missing/compute/common.py
- dataprep/eda/missing/compute/univariate.py
Optimized plot_missing(df, x) and plot_correlation(df, x, y). The main change was using dataframe API rather than array. Closes #319 
manually
`plot_missing(df, x)` example increase 47s ->6s
`plot_correlation(df, x, y)` example increase 100s -> ~1s
> perf(eda): optimize plot_missing and plot_corr

- dataprep/eda/missing/compute/common.py
- dataprep/eda/missing/render.py
Replaced ambiguous label texts and fixed wrong color mapping issue.
CI
> fix(eda.create_report): new label texts and color mapping

- dataprep/clean/__init__.py
- dataprep/clean/clean_country.py
- dataprep/clean/clean_lat_long.py
- dataprep/clean/country_data.tsv
- dataprep/clean/utils.py
- poetry.lock
- pyproject.toml
Implemented clean_country function to clean messy country names and convert them between ISO 3166 country codes.
closes #371
> feat(clean): implement clean_country function

- dataprep/tests/clean/__init__.py
- dataprep/tests/clean/test_clean_lat_long.py
This PR adds simple tests for clean_lat_long. Closes #372
> test(clean): add tests for clean_lat_long

- dataprep/clean/__init__.py
- dataprep/clean/clean_url.py
- dataprep/clean/utils.py
> feat(clean): add clean_url

- dataprep/tests/clean/test_clean_country.py
Added tests for the clean_country() and validate_country() functions. Closes #399
> test(clean): add tests for clean_country

- dataprep/clean/__init__.py
- dataprep/clean/clean_phone.py
Implements clean_phone function to parse and clean phone numbers in Canadian/US formats.
Closes #354.
See snapshots below.
Functionality:
Specify output format:
Split into components:
Fix missing country code (default=1, only fix if area code exists to avoid producing invalid phone numbers):
> feat(clean): implement clean_phone for Canadian/US formats

- dataprep/tests/clean/test_clean_email.py
> test(clean): add tests for clean_email()

- dataprep/clean/clean_phone.py
Fix broken `split` parameter for `clean_phone()`.
Manually.
> fix(clean): split parameter for clean_phone

- dataprep/eda/container.py
- dataprep/eda/correlation/__init__.py
- dataprep/eda/correlation/compute/nullivariate.py
- dataprep/eda/correlation/render.py
- dataprep/eda/missing/compute/nullivariate.py
- dataprep/eda/templates/tab_base.html
- dataprep/eda/templates/tab_base_corr.html
Fixes #394 - EDA.plot_correlation: enrich with stat. I only implemented it under the situation: plot_correlation(df) 
manually
> feat(eda): enrich plot_correlation

- dataprep/tests/clean/test_clean_phone.py
Adds tests for `clean_phone` and `validate_phone` functions. Closes #417.
> test(clean): add tests for clean_phone

- dataprep/eda/create_report/formatter.py
- dataprep/eda/distribution/compute/univariate.py
- dataprep/tests/eda/test_create_report.py
Added univariate datetime analysis to create_report. Closes #412. 
CI
> fix(eda.create_report): univar datetime analysis

- dataprep/tests/clean/test_clean_url.py
Add tests for `clean_url` function. Fixes #409 
The following functionalities were tested:
1) Default function.
2) `split` parameter
3) `inplace` parameter
4) `remove_auth` as a `boolean`
4) `remove_auth` as a `list` of strings
5) `errors` parameter
6) `validate_url` for values
7) `validate_url` for Series
> test(clean) : add test for clean_url

- dataprep/tests/connector/test_integration.py
- dataprep/utils.py
Styles raw dataframe and displays in web browser.
> feat(connector): create display dataframe function

- dataprep/clean/__init__.py
- dataprep/clean/clean_ip.py
Implement `clean_ip` function. Fixes #435 
Has been tested with a variety of values as show in the snap shot section
-----------
------------
---------------
> feat(clean) : add clean_ip function

- README.md
> docs(README): polish EDA section

- dataprep/eda/missing/compute/nullivariate.py
- dataprep/tests/eda/test_plot_missing.py
Fixes the bug mentioned in #137 
Show a screenshot in #137 
> Fixes #137 fix(eda): when data size is small using plot_missing

- dataprep/clean/clean_date.py
- dataprep/clean/clean_date_utils.py
Implementation of clean_date function. It can transform complex date format to complex target format. Meanwhile, it can handle transformation between different timezones.
1. Test fix_empty parameter, using:
* clean_date(df, 'date', fix_empty='auto_minimum')
* clean_date(df, 'date', fix_empty='empty')
* clean_date(df, 'date', fix_empty='auto_nearest')
2. Test different output format and different timezone, using:
* clean_date(df, 'date', target_format='YYYY-MM-DD')
* clean_date(df, 'date', origin_timezone='PDT', target_timezone='ChinaST',target_format='yyyy.MM.dd AD at HH:mm:ss Z')
* clean_date(df, 'date', origin_timezone='PDT', target_timezone='ChinaST',target_format='yyyy.MM.dd AD at HH:mm:ss z')
* clean_date(df, 'date', target_format='EEE, d MMM yyyy HH:mm:ss Z')
1. Test 1: …
> feat(clean):add clean_date function

- dataprep/clean/clean_country.py
- dataprep/clean/clean_email.py
- dataprep/clean/clean_ip.py
- dataprep/clean/clean_lat_long.py
- dataprep/clean/clean_phone.py
- dataprep/clean/clean_url.py
- docs/source/api_reference/dataprep.clean.rst
- docs/source/api_reference/dataprep.rst
- docs/source/user_guide/clean/clean_country.ipynb
- docs/source/user_guide/clean/clean_email.ipynb
- docs/source/user_guide/clean/clean_ip.ipynb
- docs/source/user_guide/clean/clean_lat_long.ipynb
- docs/source/user_guide/clean/clean_phone.ipynb
- docs/source/user_guide/clean/clean_url.ipynb
- docs/source/user_guide/clean/introduction.ipynb
Add the API reference for dataprep.clean.
> docs(clean): add API reference

- docs/source/user_guide/datasets/introduction.ipynb
- docs/source/user_guide/user_guide.rst
Add introduction documentation for datasets
> docs(datasets): add introduction for datasets

- dataprep/clean/clean_address.py
- dataprep/clean/clean_country.py
- dataprep/clean/clean_email.py
- dataprep/clean/clean_headers.py
- dataprep/clean/clean_ip.py
- dataprep/clean/clean_lat_long.py
- dataprep/clean/clean_phone.py
- dataprep/clean/clean_url.py
- docs/source/api_reference/dataprep.clean.rst
I changed the Docstring descriptions for clean_phone() and clean_email() functions.
> docs(clean): Docstrings for phone and email

- dataprep/clean/clean_address.py
- dataprep/clean/clean_country.py
- dataprep/clean/clean_date.py
- dataprep/clean/clean_date_utils.py
- dataprep/clean/clean_email.py
- dataprep/clean/clean_headers.py
- dataprep/clean/clean_ip.py
- dataprep/clean/clean_lat_long.py
- dataprep/clean/clean_phone.py
- dataprep/clean/clean_url.py
- dataprep/tests/clean/test_clean_date.py
- docs/source/api_reference/dataprep.clean.rst
- docs/source/user_guide/clean/introduction.ipynb
Apply the known optimizations to `clean_date`. The speed-up went from around 75s to 10s on 50000 rows.
Unit
> perf(clean): improve performance of clean_date

- dataprep/clean/clean_email.py
- dataprep/tests/clean/test_clean_email.py
improve the peformace of clean_email() based on previous practice
Yes
> perf(clean): improve the peformace of clean_email()

- dataprep/eda/distribution/compute/overview.py
- dataprep/eda/templates/grid_base.html
Fixed the incorrect variable names parsing in the dataset insight table. Closes #514.
CI
N/A
> fix(eda.distribution): highlight variable names

- README.md
In regards to the meeting, I made the following changes to the Read.me file.
- Removed Gifs of connector
- Reduced the size of the table
- Added a piece of static code to highlight easy use of Connector module
Normal unit tests done by Github Actions
> Read.Me updates

- README.md
- docs/source/user_guide/clean/clean_address.ipynb
- docs/source/user_guide/clean/introduction.ipynb
> docs(clean): improve DataPrep.Clean ReadMe

- README.md
Changed the spacing and wording in the connector section.
> connector: updated README to make it consistent with EDA and Clean

- dataprep/eda/create_report/formatter.py
- dataprep/eda/create_report/templates/correlation.html
- dataprep/eda/create_report/templates/missing.html
- dataprep/eda/create_report/templates/scripts.html
- dataprep/eda/create_report/templates/styles.html
Put Correlations and Missing Values figures into tabs.:
Pass the existing unit testings
> <fea>(eda.create_report): Change layout

- docs/source/api_reference/dataprep.connector.rst
This PR aims to update the documentation for the connector.
The tasks include:
1. Update the API reference to date.
2. Add a page for connect().
3. Add a page for .query() function.
4. Add a page to explain info() function.
Although we already have a very detailed review about the authorization schemes, pagination and concurrency feature. I found the general description for connect(), query() and info() function are missing, such as what parameters are available.
The goal of this PR will be to complete this piece.
Please comment in this thread if you have any thoughts.
@dovahcrow @jnwang @nick-zrymiak @Lakshay-sethi @h-asmat thanks!
> docs(connector): update docs

- dataprep/connector/config_manager.py
Restructure all the existing config files and changed the github directory accordingly here.
> connector: update github connector directory

- docs/source/user_guide/connector/DBLP.ipynb
adding a draft section for process overview via DBLP.
> docs(connector): adding a process overview via DBLP section

- docs/source/user_guide/connector/connect.ipynb
- docs/source/user_guide/connector/query.ipynb
Adding two draft sections for connect() and query() functions.
> docs(connector): add connect() and query() section

- dataprep/clean/__init__.py
- dataprep/clean/clean_duplication.py
- dataprep/clean/clean_duplication_utils.py
- docs/source/api_reference/dataprep.clean.rst
- poetry.lock
- pyproject.toml
Implements the clean_duplication() function for clustering and standardizing duplicate values using a front-end GUI.
Manually tested
> feat(clean): add clean_duplication() function

- dataprep/eda/create_report/formatter.py
- dataprep/eda/create_report/templates/base.html
- dataprep/eda/create_report/templates/overview.html
- dataprep/eda/create_report/templates/scripts.html
- dataprep/eda/create_report/templates/styles.html
- dataprep/eda/create_report/templates/variables.html
- dataprep/eda/distribution/compute/overview.py
- dataprep/eda/distribution/render.py
Add overview insights and column insights to create_report. Update
layout and fix bugs.
Pass existing tests
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
> feat(creat_report) add autoinsights to create_report

- dataprep/eda/create_report/templates/scripts.html
- dataprep/eda/create_report/templates/styles.html
- dataprep/eda/create_report/templates/variables.html
- dataprep/eda/distribution/render.py
Fix the previous pr comments and add highlight to stats in jupyter notebook
pass the existing tests
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
> feat(eda): create_report UI improvement

- dataprep/eda/configs.py
- dataprep/eda/container.py
- dataprep/eda/distribution/compute/univariate.py
- dataprep/eda/distribution/render.py
- dataprep/eda/templates/tab_base.html
- dataprep/eda/templates/tab_styles.html
- docs/source/user_guide/eda/parameter_configurations.ipynb
Add a value frequency table to `plot(df, x)`.
Unit
> feat(eda): value frequency table

- dataprep/clean/clean_duplication.py
- docs/source/user_guide/clean/introduction.ipynb
Fix some small `Clean` documentation bugs.
> docs(clean): fix clean documentation

- dataprep/connector/connector.py
- dataprep/connector/schema/defs.py
This PR request is in relation  to issue #544 .
In order to test it I created a mapbox named folder which contains some config file(to be deleted after PR is approved).
Alongside of it I created a juypter notebook which contains the code I used to test it.
with parse = True
With parse = false (Default)
> Feature(Connector): Function to allow dynamic website generation

- dataprep/clean/clean_duplication.py
- dataprep/clean/clean_duplication_utils.py
- docs/source/user_guide/clean/clean_duplication.ipynb
- docs/source/user_guide/clean/introduction.ipynb
Added the user guide for the clean_duplication function.
> docs(clean): add user guide for clean_duplication

- dataprep/datasets/data/patient_info.csv
- dataprep/datasets/data/waste_hauler.csv
Augment our Clean dataset with example data ('waste_hauler.csv') for demoing `clean_duplication`, and add a dataset for EDA for our medium article.
> chore(dataprep): add datasets for Clean and EDA

- dataprep/eda/correlation/__init__.py
- dataprep/eda/correlation/compute/__init__.py
- dataprep/eda/create_report/formatter.py
- dataprep/eda/distribution/compute/__init__.py
- dataprep/eda/missing/compute/__init__.py
- dataprep/eda/utils.py
- dataprep/tests/eda/random_data_generator.py
This PR test eda by randomly generate data and fix the column name and index related issues: duplicate column name/index name, column name/index name is object, object column contains multiple types in cells.
> add random data generator and fix some issues

- dataprep/eda/distribution/compute/univariate.py
- dataprep/eda/distribution/render.py
Change `nuniq` calculation for value table.
> refactor(eda): change nunique calc for value_table

- dataprep/clean/clean_duplication.py
- dataprep/clean/clean_duplication_utils.py
Improves the performance of the clean_duplication function. The improvement comes from using parallelizing with dask and also only adding the count of cluster entries and sorting by the counts on page load. 
Some rough results on my machine:
N-gram clustering a million rows went from ~90 seconds to ~60 seconds. When there is lots of clusters the improvement is not massive.
Fingerprint clustering a million rows went from ~40 seconds to ~7 seconds. This resulted in no clusters which is when improvement is largest.
Fingerprint clustering 200,000 rows went from ~0.7 seconds to ~0.5 seconds. This dataset has a lot of duplicates which results in much faster times but the difference is minimal.
For the first two results I just used `df = pd.DataFrame({"data": [str(i) for i in …
> perf(clean): improve performance of clean_duplication

- README.md
- dataprep/clean/clean_country.py
Fixes a bug in `validate_country()` with the string `" ?"`. Closes #575.
> fix(clean): fix bug in validate_country

- dataprep/eda/templates/grid_scripts.html
- dataprep/eda/templates/tab_base.html
- dataprep/eda/templates/tab_base_corr.html
- dataprep/eda/templates/tab_scripts.html
- dataprep/eda/templates/tab_styles.html
Fixed css and optimized css layouts
CI
N/A
> fix(eda): fixed and optimized css layouts

- dataprep/eda/create_report/templates/scripts.html
- docs/source/user_guide/eda/create_report.rst
- docs/source/user_guide/eda/introduction.ipynb
update user guide's datasets and redme
pass existing tests
> <docs>: update user guide's datasets and redme

- dataprep/eda/distribution/render.py
- dataprep/tests/eda/test_plot.py
I have added a test in the test_plot.py
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes
> fix(eda): fix bugs in log transformation

- dataprep/tests/clean/test_clean_duplication.py
Added unit tests for the clean_duplication function.
> test(clean): add tests for clean_duplication()

- dataprep/clean/clean_country.py
- dataprep/eda/create_report/formatter.py
- dataprep/eda/create_report/templates/base.html
- dataprep/eda/create_report/templates/correlation.html
- dataprep/eda/create_report/templates/missing.html
- dataprep/eda/create_report/templates/overview.html
- dataprep/eda/create_report/templates/scripts.html
- dataprep/eda/create_report/templates/styles.html
- dataprep/eda/create_report/templates/variables.html
- dataprep/eda/distribution/compute/overview.py
- dataprep/eda/templates/grid_base.html
- dataprep/eda/templates/grid_styles.html
- dataprep/tests/eda/random_data_generator.py
- dataprep/tests/eda/test_plot.py
- dataprep/tests/eda/test_plot_correlation.py
- dataprep/tests/eda/test_plot_missing.py
Fixed bugs come with random generated datasets
CI
N/A
> fix(eda): fixed bugs come with random generated datasets

- dataprep/eda/create_report/formatter.py
- dataprep/eda/dtypes.py
- dataprep/eda/missing/compute/common.py
- dataprep/tests/eda/random_data_generator.py
This PR detects numerical column as categorical column is its distinct values is small
manually test
> feat(eda):detect numerical as categorical when distinct number is small

- dataprep/clean/clean_df.py
`clean_df` function: conduct a set of operations that would be useful for cleaning and standardizing a full Pandas DataFrame. Closes #503.
I have tested this function using a few real-world datasets. I will also add my test function later.
> feat(clean): add clean_df function

- docs/source/user_guide/clean/clean_df.ipynb
Adds documentation for the `clean_df()` function.
> docs(clean): add documentation for clean_df

- dataprep/clean/__init__.py
- dataprep/clean/clean_df.py
Fix `__init__.py` of clean module for creating doc of `clean_df`
> fix(docs): fix docs of clean_df

- dataprep/eda/create_report/formatter.py
- dataprep/eda/distribution/compute/univariate.py
- dataprep/eda/distribution/render.py
- dataprep/tests/eda/test_create_report.py
fix the errors when a column has constant value or all the entries are nan
pass existing unit tests
> fix(eda.create_report) fix constant column error

- dataprep/eda/distribution/compute/__init__.py
- dataprep/progress_bar.py
Suppress warnings of progress bar and dask future warnings
Dask warning:
> fix(eda):suppress warnings of progress bar and dask

- dataprep/eda/create_report/__init__.py
- dataprep/eda/missing/compute/__init__.py
suppress warnings for plot_missing and create_report
> fix(eda): suppress warnings for missing and report

- dataprep/eda/distribution/compute/overview.py
infinite insight in plot(df) was calculated wrongly.
pass existing unit tests
> fix(eda): fix insight error

- dataprep/eda/container.py
- dataprep/eda/create_report/formatter.py
- dataprep/eda/create_report/templates/overview.html
- dataprep/eda/create_report/templates/styles.html
- dataprep/eda/missing/render.py
- dataprep/eda/templates/grid_base.html
- dataprep/eda/templates/grid_styles.html
- dataprep/eda/templates/tab_scripts.html
- dataprep/eda/utils.py
> fix(eda): fixed endless loop and UI issues

- dataprep/clean/clean_duplication_utils.py
This is a (potentially) bad fix for the returned DataFrame from `clean_duplication`. I think there's probably better ways to do this.
CI
> fix(clean): fix returned df_clean in clean_dupl

- dataprep/clean/clean_text.py
- docs/source/user_guide/clean/clean_text.ipynb
- docs/source/user_guide/clean/introduction.ipynb
Add documentation for `clean_text()` function.
> docs(clean): add documentation for clean_text

- dataprep/eda/dtypes.py
> fix(eda): add geopoint in type count

- dataprep/eda/create_report/formatter.py
- dataprep/eda/missing/compute/nullivariate.py
- dataprep/eda/missing/render.py
- dataprep/tests/eda/test_create_report.py
- dataprep/tests/eda/test_plot_missing.py
Close #605 
For single-column data frame, dendrogram can not be calculated and the computation of heat map needs to be edited.
pass existing unit test and new test added
> fix(eda): fix issue with dataframe of one column

- dataprep/eda/correlation/compute/__init__.py
- dataprep/eda/create_report/formatter.py
- dataprep/eda/dtypes.py
- dataprep/eda/utils.py
Currently the num columns with small distinct values will be regarded as categorical column for all plots, but it shouldn't be in correlation. This PR temporarily fix the correlation with those columns. In the future, we should regarded those columns as ordinary for all plots.
> fix(eda):fix correlation of num columns with small distinct values

- dataprep/eda/diff/__init__.py
Disable the progress bar by default to fix the blink issue of progress bar in `plot_diff`
> refactor(eda.plot_diff): disable progress bar by default

- dataprep/tests/eda/test_create_report.py
> test(eda): add dataset test for report

- dataprep/eda/create_report/formatter.py
- dataprep/eda/missing/render.py
> fix(eda): fixed uncaught dtype and long var names

- dataprep/eda/missing/render.py
- dataprep/eda/utils.py
> fix(eda):fix long name in missing heatmap

- README.md
fix titanic report link in readme
> docs(readme): fix titanc link

- dataprep/eda/create_report/formatter.py
- dataprep/eda/distribution/compute/__init__.py
- dataprep/eda/distribution/compute/overview.py
- dataprep/eda/distribution/compute/univariate.py
- dataprep/eda/eda_frame.py
- dataprep/tests/eda/random_data_generator.py
Fix categorical type error. Close #647
> eda: fix type error

- dataprep/clean/clean_duplication.py
- dataprep/clean/clean_duplication_utils.py
- poetry.lock
- pyproject.toml
The same with #648 with right format.
Also recovered #653.
> fix(clean): clean_duplication issue 646

- docs/source/user_guide/clean/clean_duplication.ipynb
Update the documentation of `clean_duplication` according to newly fixed function in #654
> perf(clean): update documentation of clean_duplication

- .github/workflows/benchmark.yml
- dataprep/connector/schema/defs.py
- dataprep/eda/create_report/formatter.py
- dataprep/tests/benchmarks/__init__.py
- dataprep/tests/benchmarks/eda.py
Add performance test for EDA by github action.
> test(eda): add performance test

- README.md
> docs(readme): add benchmark link

- dataprep/tests/eda/test_config.py
Add test for config
It is tested by Circle CI.
No
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings
- [ x ] Any dependent changes have been merged and published in downstream modules
> test(eda): add test for config

- dataprep/eda/configs.py
- dataprep/eda/container.py
- dataprep/eda/diff/compute/__init__.py
- dataprep/eda/diff/compute/multiple_column.py
- dataprep/eda/diff/render.py
- dataprep/eda/distribution/render.py
- dataprep/eda/templates/tab_base.html
- dataprep/eda/templates/tab_styles.html
- dataprep/tests/eda/test_plot_diff.py
Add stats, histogram, kde, boxplot, Pearson, Spearman, KendallTau tabs for plot_diff([df1..dfn], continuous). The existing configs for plot_diff also works. 
Unit tests added.
> <feat>(eda.diff): Add plot_diff([df1..dfn], continuous)

- dataprep/clean/clean_duplication.py
- pyproject.toml
I am the author of `python-varname` package. This PR is to adopt `python-varname` `v0.8.0`, which optimizes `argname()` to have a better performance. The way to use it in this package is also modified as encouraged.
Test settings are unchanged.
N/A.
> Adopt varname 0.8.0

- docs/source/user_guide/eda/house_price.ipynb
- docs/source/user_guide/eda/titanic.ipynb
Fix plot not show issue in doc.
> docs(eda):fix plot show

- dataprep/clean/clean_duplication.py
- poetry.lock
- pyproject.toml
> build:update varname version

- dataprep/eda/configs.py
- dataprep/eda/correlation/compute/bivariate.py
- dataprep/eda/create_report/formatter.py
- dataprep/eda/distribution/compute/bivariate.py
- dataprep/eda/distribution/render.py
- dataprep/tests/eda/test_config.py
Currently the scatter sample size did not work in `create_report`. This PR fix this issue and add sample rate param for scatter plot.
Related to #687
> fix(eda):fix scatter sample size and rate

- dataprep/clean/__init__.py
- dataprep/clean/clean_bic.py
- dataprep/clean/clean_bitcoin.py
- dataprep/clean/clean_casrn.py
- dataprep/clean/clean_cusip.py
- dataprep/clean/clean_ean.py
- dataprep/clean/clean_figi.py
- dataprep/clean/clean_grid.py
- dataprep/clean/clean_iban.py
- dataprep/clean/clean_imei.py
- dataprep/clean/clean_imo.py
- dataprep/clean/clean_imsi.py
- dataprep/clean/clean_isan.py
- dataprep/clean/clean_isbn.py
- dataprep/clean/clean_isil.py
- dataprep/clean/clean_isin.py
- dataprep/clean/clean_ismn.py
- dataprep/clean/clean_issn.py
- docs/source/api_reference/dataprep.clean.rst
- docs/source/user_guide/clean/clean_isbn.ipynb
Implement 17 clean functions for numerical types according to `stdnum` library.
Test the basic function for each clean function
1. Business identifier Codes
2. Bitcoin Addresses
3. CAS Registry Numbers
4. CUSIP numbers (financial security identification number)
5. EAN (International Article Number)
6. FIGI (Financial Instrument Global Identifier) 
7. Global Release Identifier (GRid)
8. IBAN
9. International Mobile Equipment Identity (IMEI)
10. International Maritime Organization Numbers
11. International Mobile Subscriber Identity (IMSI)
12. International Standard Audiovisual Numbers
13. ISBN
14. International Standard Identifier for Libraries (ISIL)
15. International Securities Identification Number (ISIN)
16. ISMN
17. International Standard Serial Numbers (ISSN)
> feat(clean): add 17 clean functions for number types

- dataprep/clean/__init__.py
- dataprep/clean/clean_ad_nrt.py
- dataprep/clean/clean_al_nipt.py
- dataprep/clean/clean_ar_cbu.py
- dataprep/clean/clean_ar_cuit.py
- dataprep/clean/clean_ar_dni.py
- dataprep/clean/clean_at_uid.py
- dataprep/clean/clean_at_vnr.py
- dataprep/clean/clean_lei.py
- dataprep/clean/clean_meid.py
- dataprep/clean/clean_vatin.py
- dataprep/connector/schema/defs.py
- dataprep/eda/create_report/formatter.py
Implement 10 clean functions for numerical types according to stdnum library.
Test the basic function for each clean function
1. Andorra NRT (Número de Registre Tributari, Andorra tax number)
2. NIPT (Numri i Identifikimit për Personin e Tatueshëm, Albanian VAT number).
3. CBU (Clave Bancaria Uniforme, Argentine bank account number).
4. CUIT (Código Único de Identificación Tributaria, Argentinian tax number).
5. DNI (Documento Nacional de Identidad, Argentinian national identity nr.).
6. UID (Umsatzsteuer-Identifikationsnummer, Austrian VAT number).
7. VNR, SVNR, VSNR (Versicherungsnummer, Austrian social security number).
8. Legal Entity Identifier (LEI) Numbers.
9. Mobile Equipment Identifiers (MEIDs).
10. International value added tax identification numbers.
> feat(clean): add another 10 clean functions for number types

- dataprep/eda/distribution/render.py
> fix(eda):remove imdt output from plot

- README.md
> docs(readme):add eda colab

- docs/source/api_reference/dataprep.clean.rst
- docs/source/user_guide/clean/introduction.ipynb
> add clean_ml documentation

- docs/source/user_guide/clean/clean_au_abn.ipynb
- docs/source/user_guide/clean/clean_au_acn.ipynb
- docs/source/user_guide/clean/clean_au_tfn.ipynb
- docs/source/user_guide/clean/clean_be_iban.ipynb
- docs/source/user_guide/clean/clean_be_vat.ipynb
- docs/source/user_guide/clean/clean_bg_egn.ipynb
- docs/source/user_guide/clean/clean_bg_pnf.ipynb
Fix partial clean docs to see whether it can generate right website.
> fix partial clean docs
