sfu-db/dataprep

dataprep/eda/missing/compute.py
dataprep/eda/missing/render.py

The y_range min should be smaller than the minimal value in the column for histogram otherwise some bars are compressed down to the x-axis and are not visible.
Screenshots:
Manually

fix(eda.missing): decrease the min y_range to 0

---

dataprep/eda/missing/__init__.py
dataprep/eda/missing/compute.py
dataprep/eda/missing/render.py

This fixes #44 
The current implementation will be:
If the bin size = 1, then only show a single number
otherwise, loc will be a range.
Previously, the problem is that when the num bins is smaller than the # rows, the computation will be incorrect.

Implement missing spectrum without using histogram

---

.gitignore
dataprep/data_connector/schema.json
dataprep/data_connector/types.py
dataprep/eda/correlation/render.py
dataprep/eda/missing/render.py

This PR makes it possible to define "templates" in the schema. Partially addresses #52.
A possible usage can be 
```json
{
"request": {
"params: {
"template": "{{first_name}}$_{{last_name}}$",
"required": false,
"toKey": "q",
}
}
}
```
Manually tested

feat(data-connector): support template

---

dataprep/eda/basic/compute.py
dataprep/eda/basic/render.py

Made the boxplot grow with the number of bins, and reformatted xaxis and yaxis tick values for all plots. Closes issue #104.
I tested this by inspecting the ticks and boxplots on the suicides, titanic and car_crashes datasets (ladder two from seaborn).

fix(eda): boxplot grow with bins, reformat x/yaxis

---

dataprep/eda/report.py

Windows doesn't allow a file to open twice while this is exactly what we do to create a report.
fixes #131
On my Linux machine and pending for verifying on windows

fix(eda): report permission error on windows

---

dataprep/eda/basic/compute.py
dataprep/eda/basic/render.py
dataprep/tests/eda/test_plot.py

Fixed #150 
Histogram with KDE and Q-Q plot will no longer show up when a singular value is given.
Added a singular value series in test DataFrame and a corresponding test scenario.
N/A

fix(eda.plot): fix singular value for KDE and QQ norm plot

---

dataprep/eda/report.py

Use "show" instead of "render" to show the plot since "show" is more commonly used, e.g. matplotlib.
locally.

fix(eda.report): rename render to show

---

dataprep/eda/missing/compute.py
dataprep/eda/missing/render.py
dataprep/tests/eda/test_plot_missing.py

Fixed #98
Change column type from int to object will no longer cause an error when calling
`plot_missing()`. I restored the dtypes of columns after calling dask.compute() and cast the input of FactorRange() to string. 
Change a column type in test DataFrame and add a corresponding test scenario.
N/A

fix(eda.plot_missing): fix error when change column type

---

dataprep/data_connector/schema.json
dataprep/data_connector/types.py
dataprep/tests/data_connector/test_integration.py

The API key gets added as a query string parameter instead of an auth header
Resolves #200
Adding a new authorization type `TokenParam` that can be defined in the config files since some websites like YouTube requires the key to be added as a query string parameter `key` instead of an Auth header.
When the user provides the auth token while defining the connector object, `dc = Connector(".././DataConnectorConfigs/youtube", _auth={"access_token":<auth_token>})`, a query string parameter called key is to be added to the params request object.
`'params': {'key': 'AIzaSyC2Z29ow99qyV3kdk0CJYTINYgxG48ArqM'}}`.
The changes have been tested by successfully fetching YouTube data. The other auth types are also re-tested to assure that this does not affect the existing types like Bearer and OAuth2. …

feat(data_connector): adding support for authorization type QueryParam

---

dataprep/eda/report.py

This fixes issue #102 to display plot in Colab correctly.
I test this will a minimal example `plot(df)` where df is `sns.load_dataset('titanic')`
In colab you need to install `dataprep` first with `!pip install -U tornado dataprep` then restart the runtime.

Add code to display inside Google Colab

---

dataprep/eda/basic/render.py

Changed the maximum kde yaxis tick value to be the max of the bin height or KDE value. 
Manually
Before:
Now:

fix(eda.plot): kde yaxis tick locations

---

poetry.lock
pyproject.toml

This fixes #218 
The issue is causing by bokeh 2.2.0 requires tornado >= 5.1 while kaggle only have tornado version 5.0.2.
Manually tested on kaggle.
None.

fix: downgrade tornado and bokeh version for kaggle compatibility

---

dataprep/eda/report.py
dataprep/tests/data_connector/test_integration.py
dataprep/tests/eda/test_show.py

This PR closes #247 and #222. It allows user open the report from browser by calling `plot(df).show_browser()`. This is useful when calling from the terminal.

feat(eda): add show_browser function

---

dataprep/eda/correlation/render.py

Truncate the axis tick values for plot correlation

fix(eda.correlation): truncate axis tick values

---

dataprep/eda/distribution/compute/bivariate.py
dataprep/eda/distribution/compute/common.py
dataprep/eda/distribution/compute/overview.py
dataprep/eda/distribution/compute/univariate.py
dataprep/eda/distribution/render.py

Changed `drop_null()` to `.dropna()` to increase performance. Also, we can get a minor performance increase by using skewtest on the histogram frequencies rather than computing the skew on the entire column.
Some manual tests

perf(eda.plot): changed drop_null to dropna

---

dataprep/connector/connector.py
dataprep/connector/errors.py

raises an exception when invalid parameters are passed to the query method
closes #267
Currently, the query method executes even when invalid parameters are passed by the user. The change involves raising an exception for an invalid parameter, also redirecting the user to refer to the info() method for usage examples.
Include snapshots for easier review.\

feat(data_connector): Parameter check when calling query()

---

dataprep/clean/clean_lat_long.py
dataprep/clean/utils.py

Adds a `report` parameter to `clean_lat_long()` that, if True, generates a summary report. Otherwise, no report is outputted. By default, the parameter is set to True.
Closes #348.
Manual testing.

feat(clean): add report parameter for clean_lat_long

---

dataprep/eda/create_report/formatter.py
dataprep/eda/distribution/compute/__init__.py
dataprep/eda/dtypes.py
dataprep/eda/missing/compute/__init__.py

Solved the issue #330, but used a bad method (traverse the dataframe columns before converting it into dd)
manually
No Snapshot

fix(eda): change dtype 'string' to 'object'

---

dataprep/eda/create_report/formatter.py
dataprep/eda/distribution/compute/overview.py
dataprep/eda/distribution/compute/univariate.py
dataprep/tests/eda/test_create_report.py

Make `create_report` able to handle columns containing unhashable types.

fix(eda.create_report): handle unhashable dtypes

---

dataprep/eda/missing/compute/nullivariate.py
dataprep/eda/missing/render.py
dataprep/eda/templates/tab_base.html

Fixes #367 - EDA.plot_missing: enrich with stat. I only implemented it under the situation: plot_missing(df) 
manually

feat(eda): add stat. in plot_missing

---

dataprep/clean/clean_url.py

Fix issue #402.
Add `errors` parameter to the `clean_url` function and enhance the report based upon the errors parameter.
When `errors == ignore` we keep the original values and when `errors==coerce` we replace the values with `np.nan`. In the screenshot below we can see the changes in the wording of the report based on the `errors` parameter (**underlined in red**).
This function was tested on the following dataset, which also includes non-parable / non-hashable values.

feat(clean) : add errors parameter, enhance report for clean_url

---

dataprep/eda/create_report/report.py
dataprep/tests/eda/test_create_report.py

Fixes encoding issue for report.show_browser() and add report.show() function
I also add corresponding test for report.show()
manually

fix(eda.report):encoding and show issue

---

dataprep/connector/__init__.py
dataprep/connector/assets/info.html
dataprep/connector/connector.py
dataprep/connector/info.py
dataprep/connector/info_ui.py
dataprep/connector/schema/defs.py
dataprep/tests/connector/test_integration.py
dataprep/utils.py

Changes
- Added two ways to call info function:
1. Dependent on Connector object
2. Independent from Connector object
- Created function to style and display a dataframe in a browser
Issue: #386 
Motivation: Provide guidance for Jupyter and console users to call connect and query functions.
No new dependencies are required.
Ran info for each supported website config paths (local and remote) to make sure it works.
Only does not work for Spoonacular but this isn't an info function related issue. Spoonacular also doesn't work for connect.
How to call the functions:
- info('{website_name}', update = False)
- After creating a Connector object: dc.info()
- display_dataframe(df)

feat(connector): Improve info

---

examples/DataConnector_DBLP.ipynb
examples/DataConnector_Finnhub.ipynb
examples/DataConnector_Twitter.ipynb
examples/DataConnector_Yelp.ipynb
examples/DataConnector_Youtube.ipynb

Added link to Jupyter Notebook Viewer for each example so users can view properly rendered files.
Clicked on links for each file to make sure they work.
The added cell is highlighted.

docs: add links to rendered files

---

dataprep/tests/clean/test_clean_ip.py

Add tests for `clean_ip` and `validate_ip`. The following parameters have been tested.
Add tests for `clean_ip` and `validate_ip` functions.
The following functionalities were tested:
1) Default function.
2) `input_format`="ipv4"
3) `input_format`="ipv6"
4) `output_format`="full"
5) `output_format`="hexa"
6) `output_format`="binary"
7) `output_format`="integer"
8) `validate_ip` for values
9) `validate_ip` for Series

test(clean) : add tests for clean_ip and validate_ip

---

dataprep/eda/container.py
dataprep/eda/create_report/report.py

Set encoding="utf-8" in all instances that we open a file in dataprep.eda.

fix(eda): set encoding to utf-8 when file is opened

---

dataprep/connector/config_manager.py
dataprep/connector/connector.py
dataprep/connector/generator/generator.py
dataprep/connector/schema/defs.py
dataprep/connector/utils.py
dataprep/tests/connector/test_integration.py

The PR is addressing two issues:
Parameter checking happens in dataprep `connector.py` where we check for keys in `allowed_params`. This check had to include the `from_key` to accommodate for the template params.
_Also Fixed_: Finnhub config files had the template keys mentioned differently (the `fromKey` was being passed as part of the query). This has been fixed now on the DataConnector repo along with the corresponding changes in the DBLP config files. [Needs merge of the [corresponding PR in the Data Connector repo](https://github.com/sfu-db/DataConnectorConfigs/pull/50).]
**Testing**:
`fromKey` tested in both DBLP and Finnhub.
The following was throwing an error because `first_name` and `last_name` are not directly specified as params in the config file.
`df = await …

feat(connector):from_key parameter validation

---

dataprep/eda/distribution/render.py

Fixes the malformed box plot when dtype is 'object'. Closes #469.
Unit tests

fix(eda.distribution): box plot with object dtype

---

dataprep/eda/correlation/compute/__init__.py
dataprep/eda/correlation/compute/bivariate.py
dataprep/eda/correlation/compute/overview.py
dataprep/eda/correlation/compute/univariate.py
dataprep/eda/create_report/formatter.py
dataprep/tests/eda/test_plot_correlation.py

This PR refactor `eda.correlation` by:
1. push numerical df into each subfunction, such that it is easier to support categorical correlation for each function.
2. rename nullivariate to overview, which follows the name convention from plot distribution.

refactor(eda.correlation): push numerical df into each subfunction

---

dataprep/clean/__init__.py
dataprep/clean/clean_headers.py
docs/source/api_reference/dataprep.clean.rst

Implements the `clean_headers()` function to clean column names. Design details are set out in #447.
See snapshots below.
Users can specify the case style using the `case` parameter:
Users can specify values to replace in the column names by passing in a dictionary to the `replace` parameter:
Accents are automatically removed from column names:
Removal of accents can be suppressed by setting `remove_accents=False`:
Column names duplicated by calling `clean_headers()` are automatically renamed by appending a number to the end of the duplicated column name(s):
The suffix used to append the number is inferred from the `case` type:
An example of `clean_headers()` called on the [FIFA 21 messy, raw dataset for cleaning/ exploring](https://www.kaggle.com/yagunnersya/fifa-21-messy-raw-dataset-for- …

feat(clean): add clean_headers function

---

dataprep/connector/__init__.py
dataprep/connector/info.py
dataprep/tests/connector/test_integration.py

Created a websites function so users can see supported websites to use for info and connect functions.
Ran the following code in Jupyter and Eclipse to verify actual output is expected output for Jupyter and terminal.
from dataprep.connector import websites
websites()

feat(connector): add functionality that lists supported websites

---

dataprep/eda/create_report/formatter.py
dataprep/eda/distribution/compute/bivariate.py
dataprep/eda/distribution/compute/overview.py
dataprep/eda/distribution/compute/univariate.py
dataprep/tests/eda/test_create_report.py
dataprep/tests/eda/test_plot.py

An object column will be identified as a categorical variable. But its cell may still be numerical, which will cause problem in rendering. This PR fix this issue.

fix(eda): fix the error of numerical cell in object column

---

dataprep/clean/clean_headers.py
dataprep/tests/clean/test_clean_headers.py

Adds tests for the `clean_headers` function.
Also modifies the `_rename_duplicates` private function to append numbers without a space (instead of with an underscore) for `camel` and `pascal` case styles for consistency.

test(clean): add tests for clean_headers

---

dataprep/eda/correlation/compute/__init__.py
dataprep/eda/create_report/formatter.py

Filter the warning `RuntimeWarning: overflow encountered in longlong_scalars`  which occurs when the pvalue for kendalltau correlation becomes too small and overflows the 64bit float.

chore(eda): filter warning from kendall corr

---

dataprep/clean/clean_lat_long.py

With a string like "1999/20/11", the `clean_lat_long()` regex would match "1999/" as irrelevant characters at the beginning of the string, then "20" as the latitude degrees and "11" as the longitude degrees. This PR inhibits this match.
CI

fix(clean): lat_long regex not match a date format

---

dataprep/eda/distribution/compute/overview.py
dataprep/eda/distribution/compute/univariate.py
dataprep/eda/distribution/render.py

I change the function of dask.nunique() to dask.nunique_approx() to accelerate create_reprot()
Manually

feat(eda): accelerate create_report()

---

dataprep/clean/clean_duplication_utils.py

Change the output code from `clean_duplication` from
``` python
df['col'] = df['col'].replace(['Hello', 'HELLO'], 'Hello')
```
to
``` python
df['col'] = df['col'].replace(['HELLO'], 'Hello')
```
I.e., remove the unnecessary value  from the replace list.
Unit

fix(clean): remove unneeded replace in clean_dupl

---

dataprep/assets/english_stopwords.py
dataprep/clean/__init__.py
dataprep/clean/clean_text.py
dataprep/tests/clean/test_clean_text.py
docs/source/api_reference/dataprep.clean.rst

Implements the `clean_text()` function to clean text data in a DataFrame column. Design details are set out in #571 (updated).
Unit tests.

feat(clean): add clean_text function

---

dataprep/clean/clean_country.py
dataprep/tests/clean/test_clean_country.py
docs/source/user_guide/clean/clean_country.ipynb

Adds support for cleaning multiple input formats at once by passing a tuple of input formats to the clean_country() and validate_country() functions.
closes #567
Unit tests

feat(clean): tuple of input formats for clean_country()

---

dataprep/clean/clean_duplication_utils.py

When using the export code functionality of clean_duplication() apostrophes aren't escaped in exported code.
Unit tests

fix(clean): escape apostrophes in code exported by clean_dupl

---

.pylintrc
dataprep/eda/create_report/formatter.py
dataprep/eda/distribution/compute/bivariate.py
dataprep/eda/distribution/compute/overview.py
dataprep/eda/distribution/compute/univariate.py
dataprep/eda/distribution/render.py
dataprep/eda/utils.py

Previously each cell in obj column will transform to string including missing values. This will make missing values becomes a string 'nan' rather than missing. This PR fix this issue.

fix(eda): keep missing values when preprocessing dataframe

---

dataprep/eda/create_report/formatter.py
dataprep/eda/create_report/templates/scripts.html

fix(eda): fixed uncaught dtype exceptions

---

dataprep/eda/diff/compute/__init__.py
dataprep/eda/diff/compute/multiple_df.py
dataprep/eda/distribution/__init__.py
dataprep/eda/distribution/compute/__init__.py
dataprep/eda/distribution/compute/bivariate.py
dataprep/eda/distribution/compute/trivariate.py
dataprep/eda/distribution/compute/univariate.py
dataprep/eda/dtypes.py
dataprep/tests/eda/test_plot.py
dataprep/tests/eda/test_plot_diff.py

1. Currently the NA values will first be transformed to string then displayed as categorical values. This PR avoid the transformation for na values.
2. Currently the int column may change to float when concat dfs. This PR fixs the float display for int column.

eda: fix NA and int viz issue in plot_diff

---

README.md

docs(readme):small text change on clean and connector

---

docs/source/user_guide/eda/parameter_configurations.ipynb

I have added scatter.sample_rate to both plot_correlation() and plot() parameter descriptions.

docs(eda): scattter.sample_rate added to documentation
